server:
  port: 9200
#  ssl:
#    key-store: classpath:www-tangle-ink-0901133425.pfx
#    key-store-password: dHzfY90f
#    key-store-type: PKCS12
#    enabled: true

spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://82.157.21.9:3306/hof?userSSL=false
#    url: jdbc:mysql://localhost:3306/hof?userSSL=false
    username: root
    password: 597130788
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select '1'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

local:
  storage:
    path: ''
logging:
  level:
    root: debug