server:
  port: 9200
#  ssl:
#    key-store: classpath:www-tangle-ink-0901133425.pfx
#    key-store-password: dHzfY90f
#    key-store-type: PKCS12
#    enabled: true


spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/hof?userSSL=false
    username: root
    password: "!Tang597130788"
#    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select '1'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  redis:
    host: 82.157.21.9
    database: 0
    port: 6379
    timeout: 10s
    jedis:
      pool:
        max-active: 32
        max-idle: 32
        min-idle: 1
    password: 597130788
  cache:
    redis:
      use-key-prefix: true
      key-prefix: dev
      cache-null-values: false
      time-to-live: 20s


local:
  storage:
    path: ''
logging:
  level:
    root: debug
  file:
    # 默认情况下：会在项目的根目录下生成/output/logs/spring.log，默认的日志名是：spring.log
    path: output/logs
    # 如果不想把日志存放在logging.file.path目录下，可以采用name来重新定义存储的位置和日志文件的名称
    #name: d:/output/logs/console.log
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger{50}- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm:ss} ---- [%thread] %-5level %logger{50}- %msg%n"